<Project>

  <PropertyGroup>
    <AnalysisLevel>10.0-all</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup>
    <MinVerMinimumMajorMinor>1.0</MinVerMinimumMajorMinor>
    <MinVerAutoIncrement>minor</MinVerAutoIncrement>
  </PropertyGroup>

  <ItemGroup>
    <ProjectCapability Include="DynamicFileNestingEnabled" />
  </ItemGroup>

</Project>